# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preludered', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='libretto_image',
        ),
        migrations.AddField(
            model_name='music',
            name='image',
            field=models.FileField(default='', upload_to='public/uploads/'),
        ),
    ]
