# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preludered', '0002_auto_20171108_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credits',
            name='image',
            field=models.FileField(default='', upload_to='public/uploads/'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='image',
            field=models.FileField(default='', upload_to='public/uploads/'),
        ),
    ]
