# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preludered', '0003_auto_20171108_0515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credits',
            options={'verbose_name': 'Credits', 'verbose_name_plural': 'Credits'},
        ),
        migrations.AlterModelOptions(
            name='music',
            options={'verbose_name': 'Music', 'verbose_name_plural': 'Music'},
        ),
        migrations.AlterModelOptions(
            name='musicvideos',
            options={'verbose_name': 'Music Video', 'verbose_name_plural': 'Music Videos'},
        ),
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
        migrations.AddField(
            model_name='credits',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='music',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='musicvideos',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='notes',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='credits',
            name='image',
            field=models.FileField(default='', upload_to='uploads/'),
        ),
    ]
